apiVersion: apps/v2
kind: Deployment
metadata:
  labels:
    app: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - image: olenairy/reverse-proxy
        name: reverse-proxy
        imagePullPolicy: Always          
         
        ports:
        - containerPort: 8080
      restartPolicy: Always